In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('taxi_bi.csv')

c:\users\bartosz.kosciug\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [35]:
data.sample(10)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
88065,2.0,2020-01-09 18:45:27,2020-01-09 18:50:23,N,1.0,152,152,1.0,1.02,5.50,1.00,0.5,0.0,0.00,NaN,0.3,7.30,2.0,1.0,0.00
11821,2.0,2020-01-02 12:54:03,2020-01-02 13:08:44,N,1.0,75,137,1.0,5.29,17.50,0.00,0.5,2.0,0.00,NaN,0.3,23.05,1.0,1.0,2.75
411771,NaN,2020-01-19 12:09:00,2020-01-19 12:24:00,NaN,NaN,72,222,NaN,3.43,23.31,2.75,0.0,0.0,0.00,NaN,0.3,26.36,NaN,NaN,NaN
210863,2.0,2020-01-21 09:17:56,2020-01-21 09:21:38,N,1.0,41,41,1.0,0.37,4.50,0.00,0.5,0.0,0.00,NaN,0.3,5.30,2.0,1.0,0.00
434336,NaN,2020-01-27 21:37:00,2020-01-27 21:59:00,NaN,NaN,41,3,NaN,9.05,34.69,2.75,0.0,0.0,0.00,NaN,0.3,37.74,NaN,NaN,NaN
276122,1.0,2020-01-27 07:56:14,2020-01-27 08:33:44,N,1.0,37,33,1.0,0.00,19.20,0.00,0.5,0.0,0.00,NaN,0.3,20.00,1.0,1.0,0.00
293424,2.0,2020-01-28 18:32:24,2020-01-28 18:35:55,N,1.0,134,134,1.0,0.53,4.50,1.00,0.5,0.0,0.00,NaN,0.3,6.30,2.0,1.0,0.00
364148,NaN,2020-01-07 16:41:00,2020-01-07 16:52:00,NaN,NaN,232,148,NaN,-0.65,13.65,2.75,0.5,0.0,0.00,NaN,0.3,17.20,NaN,NaN,NaN
235305,2.0,2020-01-23 14:12:20,2020-01-23 14:18:08,N,1.0,75,43,1.0,0.70,6.00,0.00,0.5,0.0,0.00,NaN,0.3,6.80,1.0,1.0,0.00
413854,NaN,2020-01-20 15:58:00,2020-01-20 16:58:00,NaN,NaN,74,39,NaN,19.24,40.40,2.75,0.0,0.0,6.12,NaN,0.3,49.57,NaN,NaN,NaN

In [40]:
data['trip_type'].describe()

count    331718.000000
mean          1.023032
std           0.150004
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           2.000000
Name: trip_type, dtype: float64

In [41]:
data['trip_type'].unique()

array([ 1.,  2., nan])

In [ ]:
numeric(1,2)